name: meetup
description: "MeetUp - Group Meetup Scheduling App"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  google_fonts: ^6.2.1
  intl: ^0.20.0
  uuid: ^4.5.1
  timeago: ^3.7.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
